2021-12-03 16:10:52,378 [ERROR] django.request: Not Implemented: /home/check_file_historical/
2021-12-03 16:17:49,330 [ERROR] django.request: HTTP Version Not Supported: /rfp/search_rfp/
2021-12-03 16:51:08,853 [ERROR] django.request: HTTP Version Not Supported: /rfp/search_rfp_new/
2021-12-03 16:57:50,340 [ERROR] django.request: Internal Server Error: /rfp/get_filter_data_rfp/
Traceback (most recent call last):
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\DMP_API\DMP_APP\views_visual_rfp.py", line 656, in get_filter_data_rfp
    'benchmark_perscent_rfp':DMP_RFP.benchmark_perscent_rfp_after_search,
AttributeError: type object 'DMP_RFP' has no attribute 'benchmark_perscent_rfp_after_search'
2021-12-03 16:57:50,740 [ERROR] django.request: Internal Server Error: /rfp/visual_ajax_1_rfp/
Traceback (most recent call last):
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\DMP_API\DMP_APP\views_visual_rfp.py", line 783, in visual_ajax_1_rfp
    app_to_app_rfp = DMP_RFP.app_to_app_rfp_after_search.copy()
AttributeError: type object 'DMP_RFP' has no attribute 'app_to_app_rfp_after_search'
2021-12-03 16:57:51,753 [ERROR] django.request: Internal Server Error: /rfp/visual_ajax_2_rfp/
Traceback (most recent call last):
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\DMP_API\DMP_APP\views_visual_rfp.py", line 1145, in visual_ajax_2_rfp
    app_to_app_rfp=DMP_RFP.app_to_app_rfp_after_search.copy()
AttributeError: type object 'DMP_RFP' has no attribute 'app_to_app_rfp_after_search'
2021-12-03 16:57:51,766 [ERROR] django.request: Internal Server Error: /rfp/visual_ajax_3_rfp/
Traceback (most recent call last):
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\DMP_API\DMP_APP\views_visual_rfp.py", line 1452, in visual_ajax_3_rfp
    temp_dash=DMP_RFP.temp_dash_after_search.copy()
AttributeError: type object 'DMP_RFP' has no attribute 'temp_dash_after_search'
2021-12-03 16:57:52,746 [ERROR] django.request: Internal Server Error: /rfp/visual_ajax_5_rfp/
Traceback (most recent call last):
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\DMP_API\DMP_APP\views_visual_rfp.py", line 2300, in visual_ajax_5_rfp
    app_to_app_rfp=DMP_RFP.app_to_app_rfp_after_search.copy()
AttributeError: type object 'DMP_RFP' has no attribute 'app_to_app_rfp_after_search'
2021-12-03 16:57:53,739 [ERROR] django.request: Internal Server Error: /rfp/visual_ajax_7_rfp/
Traceback (most recent call last):
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\DMP_API\DMP_APP\views_visual_rfp.py", line 2673, in visual_ajax_7_rfp
    vendor_name = vendor_name.lower()
AttributeError: 'list' object has no attribute 'lower'
2021-12-03 16:57:54,744 [ERROR] django.request: Internal Server Error: /rfp/visual_ajax_6_rfp/
Traceback (most recent call last):
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\DMP_API\DMP_APP\views_visual_rfp.py", line 2528, in visual_ajax_6_rfp
    pb_df=DMP_RFP.pb_df_after_search.copy()
AttributeError: type object 'DMP_RFP' has no attribute 'pb_df_after_search'
2021-12-03 16:57:55,722 [ERROR] django.request: Internal Server Error: /rfp/visual_ajax_4_rfp/
Traceback (most recent call last):
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\DRL-Team\Desktop\DMP_API\DMP_API\DMP_APP\views_visual_rfp.py", line 1777, in visual_ajax_4_rfp
    app_to_app_rfp=DMP_RFP.app_to_app_rfp_after_search.copy()
AttributeError: type object 'DMP_RFP' has no attribute 'app_to_app_rfp_after_search'
